# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dF6zebQwgWmq2NNke2kkwm_JIGc5y8X
"""

#%pip install Streamlit
#%pip install requests
"""
FOOTBALL FANTASY — BRASILEIRÃO SÉRIE A & B
Streamlit App — versão completa
"""

import streamlit as st
import sqlite3
import pandas as pd
import random
import requests
import json
import hashlib
import os
from datetime import datetime, timezone, timedelta

#
# CONFIGURAÇÃO
#

DB_PATH = "football_fantasy.db"
SERIE_A_ID = 71
SERIE_B_ID = 72
SEASON = 2026
API_BASE = "https://v3.football.api-sports.io"
MAX_PICKS = 5  # cada jogador escolhe 5 times por rodada
BONUS_POINTS = 1
WIN_POINTS = 3
DRAW_POINTS = 1

# Times padrão (fallback caso API não esteja configurada)
SERIE_A_TEAMS = [
    "Palmeiras", "Flamengo", "Fluminense", "Red Bull Bragantino",
    "Athletico PR", "Bahia", "Coritiba", "São Paulo", "Cruzeiro",
    "Corinthians", "Internacional", "Santos", "Chapecoense", "Grêmio",
    "Vasco da Gama", "Mirassol", "Botafogo", "Vitória", "Remo", "Atlético MG"
]

SERIE_B_TEAMS = [
    "Ceará", "CRB", "Novorizontino", "Criciúma", "Goiás", "Vila Nova",
    "Náutico", "Avaí", "Ponte Preta", "Londrina", "São Bernardo",
    "Botafogo SP", "América MG", "Operário", "Ituano", "Tombense",
    "Sampaio Corrêa", "ABC", "Guarani", "Chapecoense B"
]

ALL_TEAMS = sorted(set(SERIE_A_TEAMS + SERIE_B_TEAMS))

#
# UTILITÁRIOS
#

def hash_password(password: str) -> str:
    return hashlib.sha256(password.encode()).hexdigest()

def get_brasilia_time():
    utc = datetime.now(timezone.utc)
    return utc - timedelta(hours=3)

#
# BANCO DE DADOS
#

def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_database():
    conn = get_conn()
    cursor = conn.cursor()

    cursor.executescript("""
        CREATE TABLE IF NOT EXISTS players (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            is_admin INTEGER DEFAULT 0,
            created_at TEXT DEFAULT (datetime('now','-3 hours'))
        );

        CREATE TABLE IF NOT EXISTS game_rounds (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            round_number INTEGER NOT NULL UNIQUE,
            status TEXT DEFAULT 'pending',
            created_at TEXT DEFAULT (datetime('now','-3 hours'))
        );

        CREATE TABLE IF NOT EXISTS matches (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            round_number INTEGER NOT NULL,
            league TEXT NOT NULL,
            home_team TEXT NOT NULL,
            away_team TEXT NOT NULL,
            home_goals INTEGER,
            away_goals INTEGER,
            status TEXT DEFAULT 'scheduled',
            fixture_id INTEGER,
            UNIQUE(round_number, league, home_team, away_team)
        );

        CREATE TABLE IF NOT EXISTS picks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            player_id INTEGER NOT NULL,
            round_number INTEGER NOT NULL,
            team_name TEXT NOT NULL,
            FOREIGN KEY (player_id) REFERENCES players(id),
            UNIQUE(player_id, round_number, team_name)
        );

        CREATE TABLE IF NOT EXISTS matchups (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            round_number INTEGER NOT NULL,
            player1_id INTEGER NOT NULL,
            player2_id INTEGER NOT NULL,
            player1_goals INTEGER DEFAULT 0,
            player2_goals INTEGER DEFAULT 0,
            player1_points INTEGER DEFAULT 0,
            player2_points INTEGER DEFAULT 0,
            FOREIGN KEY (player1_id) REFERENCES players(id),
            FOREIGN KEY (player2_id) REFERENCES players(id)
        );

        CREATE TABLE IF NOT EXISTS standings (
            player_id INTEGER PRIMARY KEY,
            total_points INTEGER DEFAULT 0,
            bonus_points INTEGER DEFAULT 0,
            wins INTEGER DEFAULT 0,
            draws INTEGER DEFAULT 0,
            losses INTEGER DEFAULT 0,
            rounds_played INTEGER DEFAULT 0,
            total_goals INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS game_config (
            key TEXT PRIMARY KEY,
            value TEXT
        );
    """)

    # Inicializa admin padrão se não existir
    cursor.execute("SELECT id FROM players WHERE is_admin=1 LIMIT 1")
    if not cursor.fetchone():
        cursor.execute(
            "INSERT OR IGNORE INTO players (name, password_hash, is_admin) VALUES (?, ?, 1)",
            ("admin", hash_password("admin123"))
        )

    # Garante que cada jogador tenha registro na standings
    cursor.execute("""
        INSERT OR IGNORE INTO standings (player_id, total_points, bonus_points, wins, draws, losses, rounds_played, total_goals)
        SELECT id, 0, 0, 0, 0, 0, 0, 0 FROM players
    """)

    conn.commit()
    conn.close()

#
# FUNÇÕES DO BANCO
#

def get_player(player_id=None, name=None):
    conn = get_conn()
    cursor = conn.cursor()
    if player_id:
        cursor.execute("SELECT * FROM players WHERE id = ?", (player_id,))
    elif name:
        cursor.execute("SELECT * FROM players WHERE name = ?", (name,))
    else:
        cursor.execute("SELECT * FROM players ORDER BY name")
    rows = cursor.fetchall()
    conn.close()
    if player_id or name:
        return dict(rows[0]) if rows else None
    return [dict(r) for r in rows]

def get_players():
    return get_player()

def get_current_round():
    """Retorna o número da rodada ativa ou None"""
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("SELECT round_number FROM game_rounds WHERE status != 'completed' ORDER BY round_number DESC LIMIT 1")
    row = cursor.fetchone()
    conn.close()
    return dict(row)['round_number'] if row else None

def get_round_status(round_number):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("SELECT status FROM game_rounds WHERE round_number = ?", (round_number,))
    row = cursor.fetchone()
    conn.close()
    return dict(row)['status'] if row else None

def get_or_create_round(round_number):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("INSERT OR IGNORE INTO game_rounds (round_number, status) VALUES (?, 'pending')",
                   (round_number,))
    conn.commit()
    conn.close()

def set_round_status(round_number, status):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("UPDATE game_rounds SET status = ? WHERE round_number = ?", (status, round_number))
    conn.commit()
    conn.close()

def get_matches(round_number):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM matches WHERE round_number = ? ORDER BY league, home_team", (round_number,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]

def save_match(round_number, league, home_team, away_team, home_goals, away_goals, status, fixture_id=None):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT OR REPLACE INTO matches
        (round_number, league, home_team, away_team, home_goals, away_goals, status, fixture_id)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (round_number, league, home_team, away_team, home_goals, away_goals, status, fixture_id))
    conn.commit()
    conn.close()

def get_picks(player_id, round_number):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM picks WHERE player_id = ? AND round_number = ?",
                   (player_id, round_number))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r)['team_name'] for r in rows]

def save_picks(player_id, round_number, teams):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM picks WHERE player_id = ? AND round_number = ?",
                   (player_id, round_number))
    for team in teams:
        cursor.execute(
            "INSERT INTO picks (player_id, round_number, team_name) VALUES (?, ?, ?)",
            (player_id, round_number, team)
        )
    conn.commit()
    conn.close()

def get_all_picks(round_number):
    """Retorna todos os picks de uma rodada: {player_id: [team1, team2, ...]}"""
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT p.id, p.player_id, p.team_name, pl.name as player_name
        FROM picks p
        JOIN players pl ON pl.id = p.player_id
        WHERE p.round_number = ?
        ORDER BY pl.name
    """, (round_number,))
    rows = cursor.fetchall()
    conn.close()
    result = {}
    for r in rows:
        d = dict(r)
        pid = d['player_id']
        if pid not in result:
            result[pid] = {'name': d['player_name'], 'teams': []}
        result[pid]['teams'].append(d['team_name'])
    return result

def get_matchups(round_number):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT m.*, p1.name as p1_name, p2.name as p2_name
        FROM matchups m
        JOIN players p1 ON p1.id = m.player1_id
        JOIN players p2 ON p2.id = m.player2_id
        WHERE m.round_number = ?
    """, (round_number,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]

def generate_matchups(round_number):
    """Sorteia os confrontos da rodada"""
    conn = get_conn()
    cursor = conn.cursor()

    # Pega jogadores que já fizeram picks
    cursor.execute("""
        SELECT DISTINCT p.player_id, pl.name
        FROM picks p
        JOIN players pl ON pl.id = p.player_id
        WHERE p.round_number = ?
    """, (round_number,))
    players = [dict(r) for r in rows]
    random.shuffle(players)

    if len(players) <2:
        conn.close()
        return False, "Precisa de pelo menos 2 jogadores com picks para gerar confrontos."

    # Se número ímpar, um jogador fica de bye (bye = vitória automática)
    by_player = None
    if len(players) % 2 != 0:
        by_player = players.pop()

    # Limpa matchups anteriores
    cursor.execute("DELETE FROM matchups WHERE round_number = ?", (round_number,))

    # Gera pares
    for i in range(0, len(players), 2):
        if i + 1 < len(players):
            p1 = players[i]
            p2 = players[i + 1]
            cursor.execute("""
                INSERT INTO matchups (round_number, player1_id, player2_id)
                VALUES (?, ?, ?)
            """, (round_number, p1['player_id'], p2['player_id']))

    # Bye: jogador sem adversário ganha 3 pontos (vitória automática)
    if by_player:
        cursor.execute("""
            INSERT INTO matchups (round_number, player1_id, player2_id, player1_points, player2_points, player1_goals)
            VALUES (?, ?, ?, 3, 0, 999)
        """, (round_number, by_player['player_id'], by_player['player_id']))

    conn.commit()
    conn.close()
    return True, f"Confrontos gerados para {len(players)} jogadores."

def calculate_round_scores(round_number):
    """Calcula a pontuação de todos os confrontos de uma rodada"""
    conn = get_conn()
    cursor = conn.cursor()

    # Pega resultados dos matches
    cursor.execute("""
        SELECT home_team, away_team, home_goals, away_goals
        FROM matches
        WHERE round_number = ? AND status = 'finished'
    """, (round_number,))
    match_results = {}
    for r in cursor.fetchall():
        d = dict(r)
        match_results[d['home_team']] = d['home_goals']
        match_results[d['away_team']] = d['away_goals']

    # Pega todos os picks da rodada
    all_picks = get_all_picks(round_number)

    # Calcula total de gols por jogador
    player_goals = {}
    for pid, data in all_picks.items():
        total = 0
        for team in data['teams']:
            if team in match_results:
                total += match_results[team]
        player_goals[pid] = total

    # Atualiza matchups com os gols
    cursor.execute("SELECT * FROM matchups WHERE round_number = ?", (round_number,))
    matchups = cursor.fetchall()

    for m in matchups:
        m = dict(m)
        p1_id = m['player1_id']
        p2_id = m['player2_id']
        p1_goals = player_goals.get(p1_id, 0)
        p2_goals = player_goals.get(p2_id, 0)

        # Caso de bye
        if p1_id == p2_id:
            p1_points = 3
            p2_points = 0
        else:
            if p1_goals > p2_goals:
                p1_points = WIN_POINTS
                p2_points = 0
            elif p2_goals > p1_goals:
                p1_points = 0
                p2_points = WIN_POINTS
            else:
                p1_points = DRAW_POINTS
                p2_points = DRAW_POINTS

        cursor.execute("""
            UPDATE matchups
            SET player1_goals=?, player2_goals=?, player1_points=?, player2_points=?
            WHERE id=?
        """, (p1_goals, p2_goals, p1_points, p2_points, m['id']))

    # Bônus: jogador com maior somatório de gols da rodada
    if player_goals:
        max_goals = max(player_goals.values())
        bonus_players = [pid for pid, g in player_goals.items() if g == max_goals and g > 0]

        # Atualiza standings
        cursor.execute("SELECT * FROM matchups WHERE round_number = ?", (round_number,))
        updated_matchups = cursor.fetchall()

        for m in updated_matchups:
            m = dict(m)
            for pid, pts_field, goals_field in [
                (m['player1_id'], 'player1_points', 'player1_goals'),
                (m['player2_id'], 'player2_points', 'player2_goals')
            ]:
                pts = m[pts_field]
                goals = m[goals_field]
                bonus = BONUS_POINTS if pid in bonus_players else 0

                # Verifica se ganhou/perdeu/empatou
                if m['player1_id'] == m['player2_id']:  # bye
                    is_win = 1
                    is_draw = 0
                    is_loss = 0
                elif pid == m['player1_id']:
                    is_win = 1 if m['player1_goals'] > m['player2_goals'] else 0
                    is_draw = 1 if m['player1_goals'] == m['player2_goals'] else 0
                    is_loss = 1 if m['player1_goals'] < m['player2_goals'] else 0
                else:
                    is_win = 1 if m['player2_goals'] > m['player1_goals'] else 0
                    is_draw = 1 if m['player2_goals'] == m['player1_goals'] else 0
                    is_loss = 1 if m['player2_goals'] < m['player1_goals'] else 0

                cursor.execute("""
                    INSERT INTO standings (player_id, total_points, bonus_points, wins, draws, losses, rounds_played, total_goals)
                    VALUES (?, ?, ?, ?, ?, ?, 1, ?)
                    ON CONFLICT(player_id) DO UPDATE SET
                        total_points = total_points + ?,
                        bonus_points = bonus_points + ?,
                        wins = wins + ?,
                        draws = draws + ?,
                        losses = losses + ?,
                        rounds_played = rounds_played + 1,
                        total_goals = total_goals + ?
                """, (pid, pts + bonus, bonus, is_win, is_draw, is_loss, goals,
                      pts + bonus, bonus, is_win, is_draw, is_loss, goals))

    # Marca rodada como concluída
    cursor.execute("UPDATE game_rounds SET status = 'completed' WHERE round_number = ?", (round_number,))

    conn.commit()
    conn.close()
    return True, "Pontuação calculada com sucesso!"

def get_standings():
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT pl.name, s.*
        FROM standings s
        JOIN players pl ON pl.id = s.player_id
        ORDER BY s.total_points DESC, s.total_goals DESC
    """)
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]

#
# API-FOOTBALL CLIENT
#

class FootballAPIClient:
    def __init__(self, api_key):
        self.api_key = api_key
        self.headers = {
            "x-apisports-key": api_key,
            "x-apisports-format": "json"
        }

    def _get(self, endpoint, params=None):
        if not self.api_key:
            return None
        try:
            url = f"{API_BASE}/{endpoint}"
            resp = requests.get(url, headers=self.headers, params=params, timeout=15)
            if resp.status_code == 200:
                data = resp.json()
                if data.get('results', 0) > 0:
                    return data
            return None
        except Exception as e:
            st.error(f"Erro na API: {e}")
            return None

    def get_current_round(self, league_id=SERIE_A_ID):
        """Retorna a rodada atual de uma liga"""
        data = self._get("fixtures/rounds", {
            "league": league_id,
            "season": SEASON,
            "current": "true"
        })
        if data and data.get('response'):
            return data['response'][0]
        return None

    def get_round_fixtures(self, league_id, round_name):
        """Retorna todas as partidas de uma rodada"""
        data = self._get("fixtures", {
            "league": league_id,
            "season": SEASON,
            "round": round_name
        })
        if data:
            return data['response']
        return []

    def fetch_and_save_round(self, round_number):
        """Busca resultados de Série A e B e salva no banco"""
        try:
            # Tenta Série A
            round_a = self.get_current_round(SERIE_A_ID)
            fixtures_a = self.get_round_fixtures(SERIE_A_ID, f"Regular Season - {round_number}") if round_a else []

            # Tenta Série B
            round_b = self.get_current_round(SERIE_B_ID)
            fixtures_b = []
            if round_b:
                try:
                    fixtures_b = self.get_round_fixtures(SERIE_B_ID, f"Regular Season - {round_number}")
                except:
                    pass

            fixtures = []
            for f in fixtures_a:
                fixtures.append(('serie_a', f))
            for f in fixtures_b:
                fixtures.append(('serie_b', f))

            if not fixtures:
                return False, "Nenhuma partida encontrada para esta rodada."

            saved = 0
            for league, f in fixtures:
                status = f['fixture']['status']['short']
                home = f['teams']['home']['name']
                away = f['teams']['away']['name']
                home_goals = f['goals']['home']
                away_goals = f['goals']['away']
                fixture_id = f['fixture']['id']

                # Mapeia status
                is_finished = status in ('FT', 'AET', 'PEN')
                save_match(
                    round_number, league,
                    home, away,
                    home_goals, away_goals,
                    'finished' if is_finished else 'scheduled',
                    fixture_id
                )
                saved += 1

            return True, f"{saved} partidas salvas para a Rodada {round_number}."

        except Exception as e:
            return False, f"Erro ao buscar dados: {e}"

#
# INTERFACE STREAMLIT
#

def login_screen():
    st.markdown("""
    <h1 style='text-align: center;'>🏆 Football Fantasy</h1>
    <h3 style='text-align: center; color: #666;'>Brasileirão Série A & B</h3>
    <hr>
    """, unsafe_allow_html=True)

    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        with st.form("login_form"):
            name = st.text_input("Seu nome")
            password = st.text_input("Senha", type="password")
            submit = st.form_submit_button("Entrar / Cadastrar", use_container_width=True)

        if submit and name:
            conn = get_conn()
            cursor = conn.cursor()
            pw_hash = hash_password(password)
            cursor.execute("SELECT * FROM players WHERE name = ?", (name,))
            player = cursor.fetchone()

            if player:
                player = dict(player)
                if player['password_hash'] == pw_hash:
                    st.session_state['player'] = player
                    st.rerun()
                else:
                    st.error("Senha incorreta!")
            else:
                cursor.execute(
                    "INSERT INTO players (name, password_hash) VALUES (?, ?)",
                    (name, pw_hash)
                )
                conn.commit()
                # Cria registro na standings
                cursor.execute("""
                    INSERT INTO standings (player_id) VALUES (?)
                    ON CONFLICT(player_id) DO NOTHING
                """, (cursor.lastrowid,))
                conn.commit()
                st.success("Conta criada! Faça login.")
                conn.close()
                st.rerun()
            conn.close()

        st.markdown("---")
        st.markdown("""
        **🏆 Como funciona:**
        - Cada rodada, escolha **5 times** do Brasileirão Série A e B
        - Seus pontos = **soma dos gols** que esses times fizeram na rodada
        - Você é sorteado em um **confronto** contra outro jogador
        - **Vencedor = 3 pontos**, Empate = 1 ponto cada
        - **Bônus:** maior pontuação da rodada ganha +1 ponto extra
        """)

def admin_panel():
    st.header("🔧 Painel do Administrador")
    players = get_players()

    tab1, tab2, tab3, tab4 = st.tabs(["📋 Rodadas", "📊 Gerenciar Resultados", "👥 Jogadores", "⚙️ Config"])

    with tab1:
        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Iniciar Nova Rodada")
            round_num = st.number_input("Número da rodada", min_value=1, max_value=38, value=20)

            api_key = st.secrets.get("API_FOOTBALL_KEY", "")
            use_api = len(api_key) > 0

            if st.button("🚀 Iniciar Rodada", use_container_width=True):
                get_or_create_round(round_num)
                status = get_round_status(round_num)

                if use_api:
                    with st.spinner("Buscando dados da rodada na internet..."):
                        client = FootballAPIClient(api_key)
                        success, msg = client.fetch_and_save_round(round_num)
                        if success:
                            matches = get_matches(round_num)
                            finished = [m for m in matches if m['status'] == 'finished']
                            if finished:
                                set_round_status(round_num, 'picking')
                                st.success(f"Rodada {round_num} iniciada! {len(finished)} jogos com resultados carregados.")
                            else:
                                st.warning("Nenhum jogo finalizado ainda nesta rodada. Os jogadores podem ver os times e escolher.")
                                set_round_status(round_num, 'picking')
                        else:
                            st.warning(f"{msg} — você pode cadastrar resultados manualmente.")
                            set_round_status(round_num, 'picking')
                else:
                    set_round_status(round_num, 'picking')
                    st.info("Modo manual: cadastre os resultados na aba 'Gerenciar Resultados'.")
                st.rerun()

        with col2:
            st.subheader("Status Atual")
            current = get_current_round()
            if current:
                status = get_round_status(current)
                st.metric("Rodada Ativa", f"{current}ª Rodada")
                st.metric("Status", status.upper())

                if status == 'picking':
                    player_count = get_all_picks(current)
                    st.metric("Jogadores que já escolheram", len(player_count))
                elif status == 'closed':
                    matchups = get_matchups(current)
                    st.metric("Confrontos gerados", len(matchups))

                # Ações
                if status == 'picking':
                    if st.button("🔒 Fechar Picks e Sortear Confrontos", use_container_width=True):
                        success, msg = generate_matchups(current)
                        if success:
                            set_round_status(current, 'closed')
                            st.success(msg)
                            st.rerun()
                        else:
                            st.warning(msg)

                elif status == 'closed':
                    if st.button("📊 Calcular Pontuação!", use_container_width=True, type="primary"):
                        success, msg = calculate_round_scores(current)
                        if success:
                            st.success(msg)
                            st.balloons()
                            st.rerun()
                        else:
                            st.error(msg)
            else:
                st.info("Nenhuma rodada ativa. Inicie uma acima.")

    with tab2:
        st.subheader("Gerenciar Resultados dos Jogos")
        round_edit = st.number_input("Rodada para editar", min_value=1, max_value=38, value=get_current_round() or 1)

        matches = get_matches(round_edit)
        if matches:
            # Filtro por liga
            league_filter = st.selectbox("Filtrar por liga", ["Todas", "Série A", "Série B"])
            filtered = matches
            if league_filter == "Série A":
                filtered = [m for m in matches if m['league'] == 'serie_a']
            elif league_filter == "Série B":
                filtered = [m for m in matches if m['league'] == 'serie_b']

            st.info(f"Mostrando {len(filtered)} partidas. ✏️ Edite os placares diretamente:")
            for match in filtered:
                cols = st.columns([3, 1, 1, 1, 3])
                with cols[0]:
                    st.markdown(f"**{match['home_team']}**")
                with cols[1]:
                    home_goals = st.number_input(
                        f"gols {match['home_team'][:8]}",
                        value=match['home_goals'] if match['home_goals'] is not None else 0,
                        min_value=0, max_value=20,
                        key=f"h_{match['id']}",
                        label_visibility="collapsed"
                    )
                with cols[2]:
                    st.markdown("×")
                with cols[3]:
                    away_goals = st.number_input(
                        f"gols {match['away_team'][:8]}",
                        value=match['away_goals'] if match['away_goals'] is not None else 0,
                        min_value=0, max_value=20,
                        key=f"a_{match['id']}",
                        label_visibility="collapsed"
                    )
                with cols[4]:
                    st.markdown(f"**{match['away_team']}**")

                if st.button(f"💾 Salvar", key=f"save_{match['id']}"):
                    save_match(
                        round_edit, match['league'],
                        match['home_team'], match['away_team'],
                        home_goals, away_goals,
                        'finished', match['fixture_id']
                    )
                    st.success(f"{match['home_team']} {home_goals}×{away_goals} {match['away_team']} salvo!")
                    st.rerun()
        else:
            st.info("Nenhuma partida cadastrada ainda nesta rodada.")
            st.markdown("**Adicionar partida manualmente:**")
            with st.form("add_match"):
                col1, col2, col3 = st.columns([2, 1, 2])
                with col1:
                    home = st.text_input("Time da casa")
                with col2:
                    st.markdown("<br>", unsafe_allow_html=True)
                    hg = st.number_input("Gols casa", 0, 20, 0, label_visibility="collapsed")
                    st.markdown("×")
                    ag = st.number_input("Gols fora", 0, 20, 0, label_visibility="collapsed")
                with col3:
                    away = st.text_input("Time visitante")
                league = st.selectbox("Liga", ["serie_a", "serie_b"])
                if st.form_submit_button("➕ Adicionar"):
                    save_match(round_edit, league, home.strip(), away.strip(), hg, ag, 'finished')
                    st.success("Partida adicionada!")
                    st.rerun()

    with tab3:
        st.subheader(f"Jogadores Cadastrados ({len(players)})")
        for p in players:
            cols = st.columns([3, 1])
            with cols[0]:
                st.markdown(f"{'👑 ' if p['is_admin'] else '👤 '}**{p['name']}**")
            with cols[1]:
                if not p['is_admin']:
                    if st.button(f"❌ Remover", key=f"del_{p['id']}"):
                        conn = get_conn()
                        c = conn.cursor()
                        c.execute("DELETE FROM players WHERE id = ?", (p['id'],))
                        c.execute("DELETE FROM standings WHERE player_id = ?", (p['id'],))
                        conn.commit()
                        conn.close()
                        st.rerun()

    with tab4:
        st.subheader("Configuração da API")
        key_status = "✅ Configurada" if st.secrets.get("API_FOOTBALL_KEY", "") else "❌ Não configurada"
        st.markdown(f"**API-Football:** {key_status}")
        if not st.secrets.get("API_FOOTBALL_KEY", ""):
            st.warning("""
            Para buscar resultados automaticamente:
            1. Acesse https://dashboard.api-football.com/register
            2. Crie conta grátis (100 req/dia)
            3. Copie sua API key
            4. Adicione nos Secrets do Streamlit Cloud como `API_FOOTBALL_KEY`
            """)

        if st.button("🔄 Resetar banco de dados (cuidado!)"):
            if st.checkbox("Confirmo que quero apagar todos os dados"):
                os.remove(DB_PATH)
                init_database()
                st.success("Banco resetado!")
                st.rerun()

def player_dashboard(player):
    st.header(f"👋 Olá, **{player['name']}**!")
    current_round = get_current_round()

    if not current_round:
        st.info("⏳ Aguardando o administrador iniciar uma nova rodada.")
        return

    status = get_round_status(current_round)
    round_info = st.container(border=True)
    with round_info:
        col1, col2 = st.columns([2, 1])
        with col1:
            st.metric("Rodada Atual", f"{current_round}ª Rodada")
        with col2:
            st.metric("Status", status.upper())

    # Mostra partidas da rodada
    matches = get_matches(current_round)
    if matches:
        with st.expander("📋 Jogos desta rodada", expanded=True):
            for league in ['serie_a', 'serie_b']:
                league_matches = [m for m in matches if m['league'] == league]
                if league_matches:
                    league_name = "🇧🇷 Série A" if league == 'serie_a' else "🇧🇷 Série B"
                    st.markdown(f"**{league_name}**")
                    for m in league_matches:
                        if m['status'] == 'finished':
                            st.markdown(f"• {m['home_team']} **{m['home_goals']}×{m['away_goals']}** {m['away_team']}")
                        else:
                            st.markdown(f"• {m['home_team']} × {m['away_team']} _(aguardando)_")

    # Fase de picks
    if status == 'picking':
        st.markdown("---")
        st.subheader("🎯 Escolha seus 5 times")
        my_picks = get_picks(player['id'], current_round)

        # Pega todos os times disponíveis (das partidas cadastradas)
        available_teams = []
        for m in matches:
            if m['home_team'] not in available_teams:
                available_teams.append(m['home_team'])
            if m['away_team'] not in available_teams:
                available_teams.append(m['away_team'])
        available_teams = sorted(set(available_teams + ALL_TEAMS))

        selected = st.multiselect(
            f"Selecione **{MAX_PICKS} times** (já escolheu {len(my_picks)}/{MAX_PICKS})",
            options=available_teams,
            default=my_picks,
            max_selections=MAX_PICKS,
            placeholder="Clique para escolher os times..."
        )

        if st.button("💾 Salvar meus picks", use_container_width=True, type="primary"):
            if len(selected) == MAX_PICKS:
                save_picks(player['id'], current_round, selected)
                st.success(f"✅ {MAX_PICKS} times salvos com sucesso!")
                st.rerun()
            else:
                st.warning(f"Escolha exatamente {MAX_PICKS} times (você selecionou {len(selected)}).")

        # Jogadores que já escolheram
        all_picks = get_all_picks(current_round)
        st.markdown("---")
        st.markdown(f"**Jogadores que já escolheram:** {len(all_picks)}")
        for pid, data in all_picks.items():
            st.markdown(f"✅ {data['name']}")

    elif status == 'closed':
        # Mostra confrontos
        matchups = get_matchups(current_round)
        my_matchup = None
        for m in matchups:
            if m['player1_id'] == player['id'] or m['player2_id'] == player['id']:
                my_matchup = m
                break

        st.markdown("---")
        st.subheader("⚔️ Seu Confronto")
        if my_matchup:
            opponent_id = my_matchup['player2_id'] if my_matchup['player1_id'] == player['id'] else my_matchup['player1_id']
            opponent_name = my_matchup['p2_name'] if my_matchup['player1_id'] == player['id'] else my_matchup['p1_name']
            my_picks_list = get_picks(player['id'], current_round)
            opp_picks_list = get_picks(opponent_id, current_round)

            col1, col2 = st.columns(2)
            with col1:
                st.markdown(f"### 🟢 Você")
                for t in my_picks_list:
                    st.markdown(f"- {t}")
            with col2:
                st.markdown(f"### 🔴 {opponent_name}")
                for t in opp_picks_list:
                    st.markdown(f"- {t}")

            st.info("⏳ Aguardando o administrador calcular a pontuação...")
        else:
            st.info("Você não está em nenhum confronto desta rodada (talvez não tenha escolhido seus times).")

    elif status == 'completed':
        # Mostra resultado
        matchups = get_matchups(current_round)
        my_matchup = None
        for m in matchups:
            if m['player1_id'] == player['id'] or m['player2_id'] == player['id']:
                my_matchup = m
                break

        if my_matchup:
            st.markdown("---")
            st.subheader("📊 Resultado da Rodada")
            is_p1 = my_matchup['player1_id'] == player['id']
            my_goals = my_matchup['player1_goals'] if is_p1 else my_matchup['player2_goals']
            opp_goals = my_matchup['player2_goals'] if is_p1 else my_matchup['player1_goals']
            my_pts = my_matchup['player1_points'] if is_p1 else my_matchup['player2_points']
            my_bonus = 0

            # Verifica bônus
            all_picks = get_all_picks(current_round)
            player_goals = {}
            for m in matchups:
                player_goals[m['player1_id']] = m['player1_goals']
                if m['player1_id'] != m['player2_id']:
                    player_goals[m['player2_id']] = m['player2_goals']

            if player_goals:
                max_goals = max(player_goals.values())
                if player_goals.get(player['id'], 0) == max_goals and max_goals > 0:
                    my_bonus = BONUS_POINTS

            col1, col2 = st.columns(2)
            with col1:
                st.metric("Seus gols", my_goals)
            with col2:
                st.metric("Gols do adversário", opp_goals)

            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("🏆 Pontos do confronto", my_pts)
            with col2:
                st.metric("⭐ Bônus", my_bonus)
            with col3:
                st.metric("📊 Total rodada", my_pts + my_bonus)

def leaderboard_screen():
    st.header("🏆 Classificação Geral")
    standings = get_standings()

    if standings:
        df = pd.DataFrame(standings)
        df = df.rename(columns={
            'name': 'Jogador',
            'total_points': 'Pts',
            'bonus_points': 'Bônus',
            'wins': 'V',
            'draws': 'E',
            'losses': 'D',
            'rounds_played': 'R',
            'total_goals': 'Gols'
        })
        df.insert(0, '#', range(1, len(df) + 1))

        st.dataframe(
            df[['#', 'Jogador', 'Pts', 'Bônus', 'V', 'E', 'D', 'Gols', 'R']],
            use_container_width=True,
            hide_index=True,
            column_config={
                'Pts': st.column_config.NumberColumn(fontColor='#FFD700'),
                'Jogador': st.column_config.TextColumn(width='large'),
            }
        )

        st.markdown("---")
        st.markdown("🏅 **Legenda:** Pts = Pontos | V = Vitórias | E = Empates | D = Derrotas | Gols = Gols marcados | R = Rodadas")
    else:
        st.info("Nenhum dado ainda. A classificação aparece após a primeira rodada pontuada.")

#
# APP PRINCIPAL
#

def main():
    st.set_page_config(
        page_title="Football Fantasy - Brasileirão",
        page_icon="🏆",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    # CSS customizado
    st.markdown("""
    <style>
        .stApp { background: #0a0a1a; }
        .stApp h1, .stApp h2, .stApp h3 { color: #FFD700 !important; }
        .stMetric label { color: #aaa !important; }
        .stMetric [data-testid="stMetricValue"] { color: #FFD700 !important; font-size: 2em !important; }
        div[data-testid="stExpander"] { background: #1a1a2e; border: 1px solid #333; }
        .stButton button { border-radius: 8px; }
        .stButton button[kind="primary"] { background: #FFD700; color: #000; font-weight: bold; }
        .st-emotion-cache-1v7f65g .st-emotion-cache-1wmy9hl { background: #1a1a2e; }
        .stSelectbox label, .stMultiSelect label { color: #ddd !important; }
        .stTabs [data-baseweb="tab-list"] { gap: 8px; }
        .stTabs [data-baseweb="tab"] { border-radius: 6px 6px 0 0; }
    </style>
    """, unsafe_allow_html=True)

    # Inicializa DB
    init_database()

    # Sidebar
    with st.sidebar:
        st.markdown("### 🏆 Football Fantasy")
        st.markdown("Brasileirão Série A & B")

        if 'player' in st.session_state:
            player = st.session_state['player']
            st.markdown(f"👤 **{player['name']}**")

            menu = ["📊 Painel", "🏆 Classificação"]
            if player['is_admin']:
                menu.append("🔧 Admin")

            choice = st.radio("", menu, label_visibility="collapsed")

            if st.button("🚪 Sair", use_container_width=True):
                del st.session_state['player']
                st.rerun()
        else:
            choice = "login"

        # Info do campeonato
        current = get_current_round()
        if current:
            st.markdown(f"📅 Rodada atual: **{current}ª**")
        standings = get_standings()
        if standings:
            st.markdown(f"👥 Jogadores: **{len(standings)}**")

    # Renderiza página
    if 'player' not in st.session_state:
        login_screen()
    else:
        player = st.session_state['player']
        if choice == "📊 Painel":
            player_dashboard(player)
        elif choice == "🏆 Classificação":
            leaderboard_screen()
        elif choice == "🔧 Admin":
            admin_panel()

if __name__ == "__main__":
    main()